backend:
  name: github
  repo: d1sc0/hellostu.xyz # Replace with your GitHub username and repository name
  branch: master # Replace with your default branch

media_folder: 'src/content/posts/post_images'
public_folder: 'post_images'

collections:
  - name: 'posts'
    label: 'Blog Posts'
    folder: 'src/content/posts'
    create: true
    slug: '{{slug}}'
    extension: 'md'
    format: 'yaml-frontmatter'
    sortable_fields: ['title', 'pubDate']
    default_sort:
      - { field: pubDate, direction: descending }
    fields: &post_fields
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          hint: 'Used for the URL and filename',
        }
      - {
          label: 'Draft',
          name: 'draft',
          widget: 'boolean',
          default: false,
          required: false,
        }
      - { label: 'Publish Date', name: 'pubDate', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - label: 'Post Image'
        name: 'postImage'
        widget: 'object'
        fields:
          - { label: 'Image File', name: 'src', widget: 'image' }
          - { label: 'Alt Text', name: 'alt', widget: 'string' }
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        summary: '{{fields.tag}}'
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'posts_mdx'
    label: 'Blog Posts (MDX)'
    folder: 'src/content/posts'
    create: true
    slug: '{{slug}}'
    extension: 'mdx'
    format: 'yaml-frontmatter'
    sortable_fields: ['title', 'pubDate']
    default_sort:
      - { field: pubDate, direction: descending }
    fields: *post_fields

site_url: https://hellostu.xyz
display_url: https://hellostu.xyz
